### ISSUE TITLE
changing sparsity during import gives a warning

### ISSUE THREAD

**Issue by lwthatcher** [jlund3/ankura#23]
When starting up the server, I get the following warning:

> /usr/lib64/python3.4/site-packages/scipy/sparse/compressed.py:698: SparseEfficiencyWarning: Changing the sparsity structure of a csc_matrix is expensive. lil_matrix is more efficient.
>   SparseEfficiencyWarning)

**Comment by jefflund** [comment]
No longer an issue under ankura2.
