### ISSUE TITLE
Split off active and sampler into a separate repo

### ISSUE THREAD

**Issue by jefflund** [jlund3/ankura#5]
This repo will be a bit more coherent if the only thing it contains is vanilla anchor words related. The split off repo(s) will use the ankura import as a dependency, and pipeline functions which add feature columns to Q for supervised anchors, as well as contain sampling based supervised topic models and active learning.

**Comment by jefflund** [comment]
I've added a setup.py to the ankura repo, which means that it can now be installed with pip. If another package had ankura as a dependency, they would put the following into their requirements.txt
`-e git+https://github.com/jlund3/ankura#egg=ankura`
The could then run
`pip install -r requirements.txt`
and ankura would be installed on their system.

**Comment by nOkuda** [comment]
Split with commit 9dad2d358222194d9cb08d9ec79f76abd0ac0f72

**Comment by nOkuda** [comment]
By the way, the split off code now resides at https://github.com/nOkuda/activetm
